# Application name
spring.application.name=habit-tracker

# default port for Elastic Beanstalk
server.port=${SERVER_PORT:5000}

# Database connection properties
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/habit_tracker?currentSchema=public}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger (OpenAPI) properties
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.default-produces-media-type=application/json

# TODO env params
spring.flyway.enabled=${FLYWAY_ENABLED:true}
spring.flyway.validate-on-migrate=${FLYWAY_VALIDATE_ON_MIGRATE:true}
spring.flyway.baseline-on-migrate=${FLYWAY_BASELINE_ON_MIGRATE:true}
spring.flyway.baseline-version=${FLYWAY_BASELINE_VERSION:2}

# JWT properties
jwt.secret=${JWT_SECRET}
jwt.token.expires.in=${JWT_TOKEN_EXPIRES_IN:1800000}

# CORS configuration
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
cors.allowed-methods=${CORS_ALLOWED_METHODS:HEAD,GET,POST,PUT,DELETE,PATCH}
cors.allowed-headers=${CORS_ALLOWED_HEADERS:Authorization,Cache-Control,Content-Type}
