# Application name
spring.application.name=habit-tracker

# Database connection properties (local)
spring.datasource.url=jdbc:postgresql://localhost:5432/habit_tracker?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger (OpenAPI) properties
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.default-produces-media-type=application/json

# JWT properties
jwt.secret=5eMCTrCic6Efh5tTo95N4INAnyU38yLSqvXwlgA2dg8=
jwt.token.expires.in=1800000
