name: Build and Test

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -f pom.xml clean package -DskipTests

      - name: Show contents of the current working directory
        run: ls -la
      - name: Show contents of the target directory
        run: ls -la target

      # - name: Run tests
      #   run: |
      #     ./mvnw test

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: habit-tracker-springboot
          path: target/habit-tracker-springboot-0.0.1-SNAPSHOT.jar
          retention-days: 1
