name: Deploy to AWS Elastic Beanstalk

on: 
    push:
      branches:
        - main
    workflow_dispatch:

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml

  deploy-to-elastic-beanstalk:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: habit-tracker-springboot

      - name: Find JAR file
        run: |
          JAR_FILE=$(find . -name "habit-tracker-springboot-*.jar" -type f | head -1)
          echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
          existing_bucket_name: ${{ secrets.EB_BUCKET_NAME }}
          region: ${{ secrets.AWS_REGION }}
          version_label: "v-${{ github.run_number }}"
          deployment_package: ${{ env.JAR_FILE }}
          wait_for_deployment: true
          wait_for_environment_recovery: true
